name = "ccremix"
type = "javascript"
#workers_dev = true
account_id = ""
# zone_id = "Or specified with process.env.CF_ZONE_ID"
# route = "example.com/*"
compatibility_date = "2022-03-01"
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "./build/index.js"


[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.mjs"

